# Generated by Django 6.0.5 on 2026-06-27 08:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('gain_muscle', 'Gain Muscle'), ('eat_healthy', 'Eat Healthy'), ('maintain', 'Maintain Weight')], default='eat_healthy', max_length=20)),
                ('meal_plan_type', models.CharField(choices=[('none', 'No Restriction'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('gluten_free', 'Gluten Free'), ('dairy_free', 'Dairy Free'), ('low_carb', 'Low Carb'), ('high_protein', 'High Protein'), ('mediterranean', 'Mediterranean'), ('other', 'Other'), ('halal', 'Halal'), ('kosher', 'Kosher')], default='none', max_length=20)),
                ('food_avoidances', models.JSONField(default=list)),
                ('calories_per_day', models.IntegerField(default=2000)),
                ('meal_slots', models.JSONField(default=list)),
                ('meal_plan_repetition', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('unique_recipes_per_meal', models.JSONField(default=dict)),
                ('cooking_time', models.CharField(choices=[('15', '15 minutes or less'), ('30', '30 minutes or less'), ('60', '1 hour or less'), ('120', 'More than 1 hour')], default='30', max_length=3)),
                ('cooking_skill', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('household_size', models.IntegerField(default=2)),
                ('cuisine_preferences', models.JSONField(default=list)),
                ('measuring_standard', models.CharField(choices=[('imperial', 'Imperial (lbs, oz)'), ('metric', 'Metric (kg, g)')], default='metric', max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
