# Generated by Django 6.0.5 on 2026-07-11 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('stripe_price_id', models.CharField(max_length=120, unique=True)),
                ('billing_interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], max_length=10)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('trial_days', models.PositiveSmallIntegerField(default=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['amount_cents'],
            },
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('trial_extension', 'Trial Extension'), ('support_comp', 'Support Complimentary'), ('migration_grandfather', 'Migration Grandfather')], max_length=40)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_subscription_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ends_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('grandfathered', 'Grandfathered')], default='pending', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('trial_start_at', models.DateTimeField(blank=True, null=True)),
                ('trial_end_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_end_at', models.DateTimeField(blank=True, null=True)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('grace_end_at', models.DateTimeField(blank=True, null=True)),
                ('grandfather_end_at', models.DateTimeField(blank=True, null=True)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_account', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='subscriptions.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscriptionaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='subscriptions.subscriptionaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
