# Generated by Django 6.0.5 on 2026-06-30 00:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_monthlyrecipegeneration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyRecipeGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("week_start_date", models.DateField()),
                ("week_end_date", models.DateField()),
                ("requested_input", models.JSONField(default=dict)),
                ("meals_output", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_recipe_generations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-week_start_date", "-created_at"]},
        ),
        migrations.AddIndex(
            model_name="weeklyrecipegeneration",
            index=models.Index(fields=["user", "week_start_date"], name="recipes_wee_user_id_18fdcf_idx"),
        ),
        migrations.AddIndex(
            model_name="weeklyrecipegeneration",
            index=models.Index(fields=["batch_id"], name="recipes_wee_batch_i_d53eca_idx"),
        ),
    ]
