# Generated by Django 6.0.5 on 2026-06-30 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_weeklyrecipegeneration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MonthlyRecipeGeneration",
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
    ]
