# Generated by Django 6.0.5 on 2026-06-30 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_recipe_generation_jobs(apps, schema_editor):
    WeeklyRecipeGeneration = apps.get_model("recipes", "WeeklyRecipeGeneration")
    RecipeGenerationJob = apps.get_model("recipes", "RecipeGenerationJob")

    weekly_rows = WeeklyRecipeGeneration.objects.all().order_by("id")
    for weekly_row in weekly_rows:
        job = RecipeGenerationJob.objects.create(
            user_id=weekly_row.user_id,
            requested_input=getattr(weekly_row, "requested_input", {}) or {},
            status="succeeded",
        )
        weekly_row.job_id = job.id
        weekly_row.save(update_fields=["job"])


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_remove_unused_recipe_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeGenerationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_input", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="weeklyrecipegeneration",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_generations",
                to="recipes.recipegenerationjob",
            ),
        ),
        migrations.RunPython(backfill_recipe_generation_jobs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="weeklyrecipegeneration",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_generations",
                to="recipes.recipegenerationjob",
            ),
        ),
        migrations.RemoveIndex(
            model_name="weeklyrecipegeneration",
            name="recipes_wee_batch_i_d53eca_idx",
        ),
        migrations.RemoveField(
            model_name="weeklyrecipegeneration",
            name="batch_id",
        ),
        migrations.RemoveField(
            model_name="weeklyrecipegeneration",
            name="requested_input",
        ),
        migrations.AddIndex(
            model_name="weeklyrecipegeneration",
            index=models.Index(fields=["job", "week_start_date"], name="recipes_wee_job_id_2ea2f5_idx"),
        ),
    ]
