# Generated by Django 6.0.5 on 2026-06-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipegenerationjob_and_weekly_refactor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='weeklyrecipegeneration',
            new_name='recipes_wee_job_id_49bc5b_idx',
            old_name='recipes_wee_job_id_2ea2f5_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklyrecipegeneration',
            new_name='recipes_wee_user_id_213cc2_idx',
            old_name='recipes_wee_user_id_18fdcf_idx',
        ),
    ]
