# Generated by Django 6.0.5 on 2026-06-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipegenerationjob_and_weekly_refactor"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipegenerationjob",
            name="start_from_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
